networks:
  frontend_net:
  data_net:
services:
    avito_database:
      image: postgres:17
      container_name: avito_database
      ports:
        - "5435:5432"
      networks:
        - data_net
      volumes:
        - db_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 3
      restart: always
    go-service:
      networks:
        - frontend_net
        - data_net
      build:
        context: .
        dockerfile: Dockerfile
      container_name: avito_service
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        CONTAINER_DATABASE_HOST: ${CONTAINER_DATABASE_HOST}
        CONTAINER_DATABASE_PORT: ${CONTAINER_DATABASE_PORT}
        SERVER_PORT: ${SERVER_PORT}
        SERVER_READ_TIMEOUT: ${SERVER_READ_TIMEOUT}
        SERVER_WRITE_TIMEOUT: ${SERVER_WRITE_TIMEOUT}
        SERVER_GRACEFUL_SHUTDOWN_TIMEOUT: ${SERVER_GRACEFUL_SHUTDOWN_TIMEOUT}
      ports:
        - "8080:8080"
      depends_on:
        - avito_database
volumes:
    db_data: